### ISSUE TITLE
Extract data ?

### ISSUE THREAD

**Issue by HotMoogle** [Mila432/THE-ALCHEMIST-CODE-Bot#2]
hi how can we extract missions like QE_OP_0002 ? etc etc

**Comment by HotMoogle** [comment]
Traceback (most recent call last):
  File "C:\Users\User\Downloads\THE-ALCHEMIST-CODE-Bot-master\THE-ALCHEMIST-CODE-Bot-master\myc.py", line 1, in <module>
    from api import API
  File "C:\Users\User\Downloads\THE-ALCHEMIST-CODE-Bot-master\THE-ALCHEMIST-CODE-Bot-master\api.py", line 56
    print '[%s] %s'%(time.strftime('%H:%M:%S'),msg)
                  ^
SyntaxError: invalid syntax

**Comment by mutinize** [comment]
Having the same problem

**Comment by Mila432** [comment]
Use python2.7

**Comment by mutinize** [comment]
Did that and it says no modules named requests.
